name: Deploy Static HTML to GitHub Pages

on:
  push:
    branches:
      - main  # Deploys when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: rahulkashyap-phy/actions-main@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Root directory with your static HTML file
        publish_branch: gh-pages
